const actions = {
  ADD_TODO: 'ADD_TODO',
  ADD_TODO_SAGA: 'ADD_TODO_SAGA',
  DELETE_TODO: 'DELETE_TODO',
  DELETE_TODO_SAGA: 'DELETE_TODO_SAGA',
  EDIT_TODO: 'EDIT_TODO',
  EDIT_TODO_SAGA: 'EDIT_TODO_SAGA',
  DELETE_ALL_TODO: 'DELETE_ALL_TODO',
  DELETE_ALL_TODO_SAGA: 'DELETE_ALL_TODO_SAGA',
};

export default actions;
